AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.4

# Disable style/complexity cops - focus on real issues only
Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Layout/LineLength:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

# Allow both single and double quotes
Style/StringLiterals:
  Enabled: false

# Don't enforce trailing commas
Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

# Gem order doesn't matter
Bundler/OrderedGems:
  Enabled: false

# Don't nitpick about identical conditional branches
Style/IdenticalConditionalBranches:
  Enabled: false
