default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test:
  <<: *default
  database: rp_todos_test
